# Generated by Django 3.2.6 on 2021-08-30 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bid', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='progress',
        ),
        migrations.RemoveField(
            model_name='unsuccessfulbid',
            name='bid',
        ),
        migrations.AddField(
            model_name='successfulbid',
            name='total_due',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bid',
            name='number_of_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bid',
            name='price_per_token',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='successfulbid',
            name='number_of_tokens_allotted',
            field=models.IntegerField(default=0),
        ),
    ]
