# Generated by Django 3.2.6 on 2021-09-01 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bid', '0002_auto_20210830_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
